global:
  scrape_interval: 15s
scrape_configs:
    - job_name: 'spring_boot_app'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['testapp-env.eba-qxcsnpmj.eu-central-1.elasticbeanstalk.com:8080']